name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'corretto'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build

    - name: Grant Permissions to gradlew
      run: chmod +x gradlew

    - name: Verify Javadoc
      run: gradle javadoc
    
    - name: Test
      run: gradle test --tests "*"

    - name: Test Success
      if: success()
      uses: actions/github-script@0.2.0
      with:
        github-token: ${{ github.token }}
        script: |
          const pull_number = "${{github.event.number}}"
          await github.pulls.createReview({
            ...context.repo,
            pull_number,
            body: "All tests passed.",
            event: "APPROVE"
          })
    - name: Test Fail
      if: failure()
      uses: actions/github-script@0.2.0
      with:
        github-token: ${{ github.token }}
        script: |
          const pull_number = "${{github.event.number}}"
          await github.pulls.createReview({
            ...context.repo,
            pull_number,
            body: "There is something wrong with test codes.",
           event: "REQUEST_CHANGES"
          })
          await github.pulls.update({
            ...context.repo,
            pull_number,
            state: "closed"
          })
